02-javascript-data-types
js-tasks-ru/js-20220111_moiseevaviktoriya pull request #2
Opened 2022-01-15 08:59 UTC by viktoriyaMoiseeva

2022-01-15 09:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-15 10:05 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-16 15:51 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-17 16:32 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return param === 'asc' ? arrCopy : arrCopy.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-01-17 16:34 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  if (a.toLowerCase() === b.toLowerCase() && a > b) {
подумайте как упростить функцию... может ли помочь вот такая операция `a - b`?

2022-01-17 16:35 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let arrCopy = arr.slice().sort(sortArray);
проверьте, тут наверное `const`?

2022-01-17 16:35 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    return fields.indexOf(entry[0]) >= 0;
проверьте, может тут лучше подойдет `includes`?

2022-01-17 16:35 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let pickedObj;
подумайте, нужна ли вообще здесь переменная `pickedObj`?

2022-01-17 16:36 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>  export const omit = (obj, ...fields) => {
аналогичные комментарии как в `pick`

2022-01-17 16:36 UTC, dosandk requested changes
необходимо внести изменения согласно комментариев

2022-01-17 20:19 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-18 14:32 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return arr.slice().sort((a, b) => {
👍 good

2022-01-18 14:33 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
>    let entries = Object.entries(obj);
проверьте, а точно ли тут `let`?
может `const`?

2022-01-18 14:33 UTC, dosandk approved these changes
👍 good

2022-01-18 14:33 UTC, merged